alias shut='shutdown now'
alias gs='git status '
alias ga='git add '
alias gb='git branch '
alias gc='git commit -v '
alias gl='git log -c'
alias gp='git push '
alias gdiff='git diff '
alias please='sudo '
alias woman='man'
alias irssi='TERM=screen-256color irssi'
alias clipboard='xclip -selection c'
alias bim='vim'
alias mux='tmux '
alias clea='clear'
alias sl='ls'
alias l='ls'
alias t="task"
